version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8u181-jdk-browsers
    steps:
    - checkout
    - run:
        name: Download Selenium & Maven
        command: |
          cat /etc/*-release
          curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
          sudo apt -qq update
          sudo apt -qq install maven
          mvn -version
          which mvn
    - run:
        name: Setup Paths
        command: "export M2_HOME=/opt/apache-maven/ >> $BASH_ENV \necho $M2_HOME\necho $PATH\necho $JAVA_HOME\n"
    - run:
        name: testng_BrandAccount_TVConversions1
        command: |
          pwd
          ls -lah
          # java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          mkdir seleniumgrid
          mvn -Dsurefire.suiteXmlFiles=testng_BrandAccount_TVConversions1.xml test
        background: false
    - run:
        name: Reports
        command: |
          pwd
          ls -lrht
          cp target/surefire-reports/Extent.html test-output/Extent.html
        when: always
        background: false
    - store_test_results:
        path: test-output
    - store_artifacts:
        path: test-output
        destination: html
workflows:
  version: 2
  workflow:
    jobs:
    - build
